# Generated by Django 4.1 on 2022-08-25 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('party', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('rm', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('voted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SecondTurn',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urna.candidate')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urna.citizen')),
            ],
        ),
        migrations.CreateModel(
            name='FirstTurn',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urna.candidate')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urna.citizen')),
            ],
        ),
    ]
