# Generated by Django 4.1 on 2022-08-31 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urna', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='password',
        ),
    ]
