# Generated by Django 4.1 on 2022-08-21 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urna', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Votante',
            new_name='Citizen',
        ),
    ]
