# Generated by Django 4.1 on 2022-08-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='voted',
            field=models.BooleanField(default=False),
        ),
    ]
