# Generated by Django 4.1.1 on 2022-09-09 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urna', '0002_remove_citizen_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_turn', models.BooleanField(default=False)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urna.candidate')),
                ('citizen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urna.citizen')),
            ],
        ),
        migrations.RemoveField(
            model_name='secondturn',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='secondturn',
            name='citizen',
        ),
        migrations.DeleteModel(
            name='FirstTurn',
        ),
        migrations.DeleteModel(
            name='SecondTurn',
        ),
    ]
