# Generated by Django 4.1.1 on 2022-09-13 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urna', '0003_turns_remove_secondturn_candidate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ndTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urna.candidate')),
                ('citizen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urna.citizen')),
            ],
        ),
        migrations.CreateModel(
            name='stTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urna.candidate')),
                ('citizen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urna.citizen')),
            ],
        ),
        migrations.DeleteModel(
            name='Turns',
        ),
    ]
