# Generated by Django 4.1.1 on 2022-09-14 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urna', '0005_candidate_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_ndTurn',
            field=models.BooleanField(default=False),
        ),
    ]
