# Generated by Django 4.1.1 on 2022-09-14 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urna', '0006_candidate_is_ndturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='getWinner',
            field=models.BooleanField(default=False),
        ),
    ]
